name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: [ "bug", "triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: 问题描述(Bug description)
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: markdown
    id: media
    attributes:
      label: 截图或GIF(Media)
      description: Please provide detailed screenshots to elaborate on the issue
    validations:
      required: true
  - type: input
    id: idea-version
    attributes:
      label: IDE 版本(Jetbrains IDE version)
      description: you can check via About dialog in the Help or App menu
      value: "IntelliJ IDEA 2025.1.3 (Community Edition)"
    validations:
      required: true
  - type: input
    id: theme-version
    attributes:
      label: 主题版本(Falcon Relaxing-Eyes Themes version)
      description: You can see the version number of the theme in the installed plugins
      value: "3.0.1"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 使用哪一个主题(Which theme?)
      description: Please select the theme you are currently using! If multiple themes have the same problem, please select multiple!
      multiple: true
      options:
        - Relax Light Green
        - Relax Light Green Contrast
        - Relax Light Celadon
        - Relax Light Grey
        - Relax Light Pink
        - Relax Light Yellow
        - Relax Dark
        - Relax Dark Blue
        - Relax Dark Coffee
        - Relax Dark Darcula
        - Relax Dark Green
        - Relax Dark Violet
      default: 0
    validations:
      required: true
